stages:
  - build
  - test

osx-build:
  stage: build
  before_script:
    - brew uninstall -f aktualizr
  script:
    - brew tap advancedtelematic/otaconnect
    - brew install --HEAD -v ./aktualizr.rb
    - aktualizr --version
  tags:
    - osx

osx-test:
  stage: test
  script:
    # consider triggering some of the aktualizr tests at this stage
    - aktualizr --version
  tags:
    - osx
